name: QuartoDockerGoGo

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: okatsn/in-my-quarto-space@main
        # See https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#example-using-a-public-action
      # Use the output from the `hello` step
      - name: Julia run
        run: julia --project=@. -e 'pwd()'
      - name: Quarto render
        run: |
          echo "quarto rendering..."
          quarto render hello/hello.qmd
          ls -la hello
