name: QuartoDockerGoGo

on: [push]

# See [Running jobs in a container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container) and
# [2 Ways to Use Your Own Docker Image in Github Actions](https://yonatankra.com/2-ways-to-use-your-docker-image-in-github-actions/)
#
# Also see (Not used in this script) https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/ and https://docs.docker.com/build/ci/github-actions/
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: okatsn/my-quarto-space
      options: --user jovyan # in response to the ERROR: IOError: mkdir("/github/home/.julia"; mode=0o777): permission denied (EACCES)
      # the Checkout step also failed for the same reason, see https://github.com/actions/checkout/issues/1014 and https://github.com/actions/checkout/issues/956
    name: A job to say hello
    steps:
      - name: Julia run at startup directory
        run: |
          julia --project=@. -e 'show(pwd())'
          ls -la
      - name: Make IJulia available for quarto
        run: |
          julia --project=@. -e 'using Pkg; Pkg.instantiate(); println("Current directory: $(pwd())"); Pkg.status()'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Julia run at checked out directory
        run: julia --project=@. -e 'show(pwd())'
      - name: Check available kernels
        run: |
          jupyter kernelspec list
          jupyter --paths
      - name: Quarto render
        run: |
          quarto render hello/hello.qmd
          ls -la hello
      # CHECKPINT: ERROR: Jupyter kernel 'julia-1.9' not found
      # https://github.com/JuliaLang/IJulia.jl/issues/1062
